export type RootStackParamList = {
  Login: undefined;
  Onboarding: undefined;
  SetPassword: undefined;
  ClientVerification: undefined;
  Admin: undefined;
  MainTabs: undefined;
  SearchModal: undefined;
  SpaceDetail: { id: string };
  VisiterDetail: { id: string };
  Checkout: { id: string; type: 'space' | 'visiter' };
  PaymentSuccess: { bookingId: string };
  CheckIn: { bookingId: string };
  ChatDetail: { id: string };
  AddPetModal: undefined;
  HostOnboarding: undefined;
  TrustAndSafety: undefined;
  HostDashboard: undefined;
  InsuranceClaim: undefined;
  EditProfile: undefined;
  LeaveReview: { bookingId: string; hostId: string; hostName: string };
  ManageService: { type: 'space' | 'visiter' };
};
