export type RootStackParamList = {
  Login: undefined;
  Onboarding: undefined;
  SetPassword: { variant?: 'onboarding' | 'recovery' | 'change' } | undefined;
  ClientVerification: undefined;
  Admin: undefined;
  MainTabs: undefined;
  SearchModal: undefined;
  SpaceDetail: { id: string };
  VisiterDetail: { id: string };
  Checkout: { id: string; type: 'space' | 'visiter' };
  TransferInstructions: { bookingId: string; amount: number };
  ChatDetail: { id: string };
  AddPetModal: { petId?: string } | undefined;
  HostOnboarding: undefined;
  TrustAndSafety: undefined;
  HostDashboard: undefined;
  InsuranceClaim: undefined;
  EditProfile: undefined;
  LeaveReview: { bookingId: string; hostId: string; hostName: string; variant?: 'host' | 'client' };
  ManageService: { type: 'space' | 'visiter'; serviceId?: string };
  Notifications: undefined;
};
